name:                aoc2020
version:             0.1.0.0
github:              "samcoy3/advent-of-code-2020"
license:             BSD3
author:              "Sam Coy"
maintainer:          "samcoy3@gmail.com"
copyright:           "2020 Sam Coy"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         My Advent of Code solutions for 2020, written in Haskell.

dependencies:
- base >= 4.7 && < 5
- directory
- optparse-applicative
- parser-combinators
- attoparsec
- containers
- text
- mtl
- vector
- pointedlist

library:
  source-dirs: src
  default-extensions:
    - EmptyCase
    - FlexibleContexts
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - TupleSections
    - OverloadedStrings
    - ScopedTypeVariables
    - GADTs
    - NumericUnderscores
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - TypeApplications

executables:
  aoc-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - EmptyCase
    - FlexibleContexts
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - TupleSections
    - OverloadedStrings
    - ScopedTypeVariables
    - GADTs
    - NumericUnderscores
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - TypeApplications
    dependencies:
    - aoc2020
